# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Renderer_config = debug
  ToneMapper_config = debug
  PhotonMapper_config = debug
  Tests_config = debug
endif
ifeq ($(config),release)
  Renderer_config = release
  ToneMapper_config = release
  PhotonMapper_config = release
  Tests_config = release
endif

PROJECTS := Renderer ToneMapper PhotonMapper Tests

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Renderer:
ifneq (,$(Renderer_config))
	@echo "==== Building Renderer ($(Renderer_config)) ===="
	@${MAKE} --no-print-directory -C . -f Renderer.make config=$(Renderer_config)
endif

ToneMapper:
ifneq (,$(ToneMapper_config))
	@echo "==== Building ToneMapper ($(ToneMapper_config)) ===="
	@${MAKE} --no-print-directory -C . -f ToneMapper.make config=$(ToneMapper_config)
endif

PhotonMapper:
ifneq (,$(PhotonMapper_config))
	@echo "==== Building PhotonMapper ($(PhotonMapper_config)) ===="
	@${MAKE} --no-print-directory -C . -f PhotonMapper.make config=$(PhotonMapper_config)
endif

Tests:
ifneq (,$(Tests_config))
	@echo "==== Building Tests ($(Tests_config)) ===="
	@${MAKE} --no-print-directory -C . -f Tests.make config=$(Tests_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Renderer.make clean
	@${MAKE} --no-print-directory -C . -f ToneMapper.make clean
	@${MAKE} --no-print-directory -C . -f PhotonMapper.make clean
	@${MAKE} --no-print-directory -C . -f Tests.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Renderer"
	@echo "   ToneMapper"
	@echo "   PhotonMapper"
	@echo "   Tests"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"